server:
  port: 8082
  servlet:
    context-path: /resource

spring:
  datasource:
    url: jdbc:mysql://192.168.128.5:3306/test?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver